### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by TheFluffyDragon** [jacklul/e621-Pool-Downloader#1]
entering login info into the .cfg doesnt work. You gave no info on what goes first, password, email, username, spacing or anything. Entering 
"username password" gives 
Empty or invalid result from the API!
Array
(
    [success] =>
    [message] => SessionLoader::AuthenticationFailure
    [code] =>
)
Press
removing the password or username gives the same error.

**Comment by jacklul** [comment]
See `config.cfg.example`:

```
; Your e621 login
LOGIN=

; API key obtained in "e621 -> Account -> Manage API Access"
API_KEY=
```

**Comment by TheFluffyDragon** [comment]
entering username and password after LOGIN= doesnt work.

**Comment by jacklul** [comment]
> entering username and password after LOGIN= doesnt work.

You enter your username in LOGIN and api key in API_KEY, you do not authenticate using password.

**Comment by TheFluffyDragon** [comment]
That should prob be stated. normally i see password needed, when seeing login on can be confused thinking password is needed. listing "username" would be better

**Comment by jacklul** [comment]
It's too late to change that now, I've updated the description in newest release though
